---
abstract: 'load YAML from cache or disk, whichever seems better'
author:
  - 'Binary <binary@cpan.org>'
build_requires:
  File::Temp: '0.23'
  Test::Most: '0.34'
  Test::RedisServer: '0.14'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YAML-CacheLoader
requires:
  Cache::RedisDB: '0.05'
  Path::Tiny: '0.061'
  Sereal: '3.005'
  YAML: '1.13'
version: '0.005'
